# Configurare pentru Render.com
services:
  - type: web
    name: whatsapp-messenger
    env: node
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: WHATSAPP_API_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false