services:
  - type: web
    name: whatsapp-messaging-app
    env: node
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 5000
    autoDeploy: true